# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d9e25537407a6d6c346daa204084e33b5af1b679ca7efd5b05f9fae9e12605eedc19b0aae2b3e0e1e59a6936e7c5fea4072a63be35e45121cedece0af2ab18f

test:
  secret_key_base: 80a0e74e448fc7f64fc34b6789aa88ee8920d26597a0d7cf6dba2d5c794f58ddc1ba0b97a99510ec6b33cf02421fa2fc668e6ab28ea9e5cc8c333f86bdb2871a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
